### ISSUE TITLE
Missing Python Requests module

### ISSUE THREAD

**Issue by dlenz** [linuxserver/docker-tvheadend#154]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
/usr/bin/tvhmeta should request metadata without error from tvdb.com when adding a new recording

## Current Behavior

/usr/bin/tvhmeta returns error "No module named requests" and no metadata is returned
## Steps to Reproduce

1. Check "Fetch artwork for new recordings" in 'Configuration' -> 'Recording' -> 'Artwork Settings' under the profile that you are using for recording
2. Select show from EPG tab and choose 'Record'
3. View logs to see error

Workaround is to run the following inside the container:
    
    apk add py-pip
    pip install requests

## Environment
**OS: CentOS 8      
**CPU architecture:** x86_64      
**How docker service was installed: dnf      

## Docker logs

2020-02-06 20:59:30.508 spawn: 2020-02-06 20:59:30,507:ERROR:tvhmeta:100:Could not import module tv_meta_tmdb when searching for supports_movie: No module named requests
2020-02-06 20:59:30.508 spawn: Traceback (most recent call last):
2020-02-06 20:59:30.508 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-06 20:59:30.508 spawn:     mod = __import__(module_name)
2020-02-06 20:59:30.508 spawn:   File "/usr/bin/./tv_meta_tmdb.py", line 22, in 
2020-02-06 20:59:30.508 spawn:     import requests
2020-02-06 20:59:30.508 spawn: ImportError: No module named requests
2020-02-06 20:59:30.509 spawn: 2020-02-06 20:59:30,509:ERROR:tvhmeta:100:Could not import module tv_meta_tvdb when searching for supports_movie: No module named requests
2020-02-06 20:59:30.509 spawn: Traceback (most recent call last):
2020-02-06 20:59:30.509 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-06 20:59:30.509 spawn:     mod = __import__(module_name)
2020-02-06 20:59:30.509 spawn:   File "/usr/bin/./tv_meta_tvdb.py", line 29, in 
2020-02-06 20:59:30.509 spawn:     import requests
2020-02-06 20:59:30.509 spawn: ImportError: No module named requests
2020-02-06 20:59:30.512 spawn: 2020-02-06 20:59:30,511:ERROR:tvhmeta:100:Could not import module tv_meta_tmdb when searching for supports_tv: No module named requests
2020-02-06 20:59:30.512 spawn: Traceback (most recent call last):
2020-02-06 20:59:30.512 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-06 20:59:30.512 spawn:     mod = __import__(module_name)
2020-02-06 20:59:30.512 spawn:   File "/usr/bin/./tv_meta_tmdb.py", line 22, in 
2020-02-06 20:59:30.512 spawn:     import requests
2020-02-06 20:59:30.512 spawn: ImportError: No module named requests

**Comment by tobbenb** [comment]
Please test if it works using this as the repository lspipepr/tvheadend:amd64-221c29b4-pkg-17369640-pr-157
That is for x86, if you are running arm, substitute amd64 with arm32v7 or arm64v8

**Comment by dlenz** [comment]
Same problem with that image:

`> docker ps | grep tvh
00a6ec7be4da        lspipepr/tvheadend:amd64-221c29b4-pkg-17369640-pr-157   "/init"  21 minutes ago  Up 21 minutes 0.0.0.0:9981-9982->9981-9982/tcp   tvh`

`2020-02-13 20:32:47.997 dvr: entry c0254a7d72492db818bbed4a6aa132f2 "The Rifleman" on "MeTV   " starting at 2020-02-13 20:29:30, with broadcast id "ddprogid:///usr/bin/tv_grab_zz_sdjson_sqlite/EP00018627.0149", scheduled for recording by "admin"
2020-02-13 20:32:47.997 dvr: "The Rifleman" on "MeTV   " recorder starting
2020-02-13 20:32:48.042 spawn: Executing "/usr/bin/tvhmeta"
2020-02-13 20:32:48.045 mpegts: 207.028MHz in OTA - tuning on LG Electronics LGDT3306A VSB/QAM Frontend #1 : ATSC-T #0
2020-02-13 20:32:48.046 subscription: 0001: "DVR: The Rifleman" subscribing on channel "MeTV   ", weight: 500, adapter: "LG Electronics LGDT3306A VSB/QAM Frontend #1 : ATSC-T #0", network: "OTA", mux: "207.028MHz", service: "MeTV   ", profile="pass", username="admin"
2020-02-13 20:32:48.578 spawn: 2020-02-13 20:32:48,577:ERROR:tvhmeta:100:Could not import module tv_meta_tmdb when searching for supports_movie: No module named requests
2020-02-13 20:32:48.578 spawn: Traceback (most recent call last):
2020-02-13 20:32:48.578 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-13 20:32:48.578 spawn:     mod = __import__(module_name)
2020-02-13 20:32:48.578 spawn:   File "/usr/bin/./tv_meta_tmdb.py", line 22, in 
2020-02-13 20:32:48.578 spawn:     import requests
2020-02-13 20:32:48.578 spawn: ImportError: No module named requests
2020-02-13 20:32:48.579 spawn: 2020-02-13 20:32:48,579:ERROR:tvhmeta:100:Could not import module tv_meta_tvdb when searching for supports_movie: No module named requests
2020-02-13 20:32:48.579 spawn: Traceback (most recent call last):
2020-02-13 20:32:48.579 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-13 20:32:48.579 spawn:     mod = __import__(module_name)
2020-02-13 20:32:48.579 spawn:   File "/usr/bin/./tv_meta_tvdb.py", line 29, in 
2020-02-13 20:32:48.579 spawn:     import requests
2020-02-13 20:32:48.579 spawn: ImportError: No module named requests
2020-02-13 20:32:48.582 spawn: 2020-02-13 20:32:48,582:ERROR:tvhmeta:100:Could not import module tv_meta_tmdb when searching for supports_tv: No module named requests
2020-02-13 20:32:48.582 spawn: Traceback (most recent call last):
2020-02-13 20:32:48.582 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-13 20:32:48.582 spawn:     mod = __import__(module_name)
2020-02-13 20:32:48.582 spawn:   File "/usr/bin/./tv_meta_tmdb.py", line 22, in 
2020-02-13 20:32:48.582 spawn:     import requests
2020-02-13 20:32:48.582 spawn: ImportError: No module named requests
2020-02-13 20:32:48.584 spawn: 2020-02-13 20:32:48,583:ERROR:tvhmeta:100:Could not import module tv_meta_tvdb when searching for supports_tv: No module named requests
2020-02-13 20:32:48.584 spawn: Traceback (most recent call last):
2020-02-13 20:32:48.584 spawn:   File "/usr/bin/tvhmeta", line 89, in _get_meta_grabbers_for_capability_common
2020-02-13 20:32:48.584 spawn:     mod = __import__(module_name)
2020-02-13 20:32:48.584 spawn:   File "/usr/bin/./tv_meta_tvdb.py", line 29, in 
2020-02-13 20:32:48.584 spawn:     import requests
2020-02-13 20:32:48.584 spawn: ImportError: No module named requests`

**Comment by tobbenb** [comment]
Probably due to being python 3 and python 2 is used by tvheadend i would guess.
It's py2-requests that gets installed by pip?
I installed the available package in the alpine repo.

**Comment by dlenz** [comment]
Yep, using python v2.7

```
root@4b0cfeb0135c:/# python --version
Python 2.7.16
root@4b0cfeb0135c:/# pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
```
